apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: web
      image: kubedevio/web-page:blue
      ports:
        - containerPort: 80
---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod-label
  labels:
    app: web
spec:
  containers:
    - name: web
      image: kubedevio/web-page:blue
      ports:
        - containerPort: 80
---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod-label2
  labels:
    app: web
    version: v1
spec:
  containers:
    - name: web
      image: kubedevio/web-page:blue
      ports:
        - containerPort: 80
